version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          PGPORT: 5432
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-core/package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-plugin/package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-server/package.json" }}

      - run:
          command: lerna bootstrap

      - save_cache:
          paths:
            - node_modules
            - packages/comments-backend-core/node_modules
            - packages/comments-backend-hapi-plugin/node_modules
            - packages/comments-backend-hapi-server/node_modules
          keys:
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-core/package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-plugin/package.json" }}
            - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "packages/comments-backend-hapi-server/package.json" }}


      - run:
          command: lerna run sanity