version: '2'
services:
  postgres:
    image: postgres:10
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGPORT: 5433
      PGDATA : /var/lib/postgresql/data/pgdata
    tmpfs:
      - /tmp
      - /var/run/postgresql
      - /var/lib/postgresql/data/pgdata:rw
